
#- name: Disable SELinux
# selinux:
#   state: disabled
#- name: Reboot soufe1
# ansible.builtin.reboot:
#   reboot_timeout: 3600
#
- name: Update dnf cache
  dnf:
    update_cache: 'yes'

- name: Install Podman
  dnf:
    name: podman
    state: present

- name: Enable and start Podman
  systemd:
    name: podman.socket
    enabled: true
    state: started

