- name: pull image grafana
  podman_image:
    name: docker.io/grafana/grafana
    tag: latest

- name: Create data dir
  ansible.builtin.file:
    path: /containers_vols/grafana/config
    state: directory
    mode: '0755'

- name: update grafana config
  ansible.builtin.copy:
    src: ../templates/grafana.j2
    dest: /containers_vols/grafana/config/grafana.ini
    mode: '0664'

#- name: Run Grafana1
#  containers.podman.podman_container:
#    name: grafana1
#    image: docker.io/grafana/grafana
#    detach: true
#    restart_policy: always
#    ports:
#      - '3000:3000'
#    volumes:
#      - '/containers_vols/grafana/config/grafana.ini:/etc/grafana/grafana.ini:z'
#    state: started

- name: Run Grafana containers
  containers.podman.podman_container:
    name: "grafana{{ item }}"
    image: docker.io/grafana/grafana
    detach: true
    restart_policy: always
    ports:
      - "{{ 3000 + item }}:3000"  # Dynamically assign unique host ports
    volumes:
      - '/containers_vols/grafana/config/grafana.ini:/etc/grafana/grafana.ini:z'
    state: started
  loop:
    - 1
    - 2
    - 3  # Now includes 3 containers: grafana1, grafana2, grafana3
  tags:
    - grafana