- name: pull image grafana
  podman_image:
    name: docker.io/grafana/grafana
    tag: latest

- name: Create data dir
  ansible.builtin.file:
    path: /containers_vols/grafana/config
    state: directory
    mode: '0755'

- name: update grafana config
  ansible.builtin.copy:
    src: ../templates/grafana.j2
    dest: /containers_vols/grafana/config/grafana.ini
    mode: '0664'

- name: Run Grafana containers
  containers.podman.podman_container:
    name: "grafana{{ item }}"
    image: docker.io/grafana/grafana
    detach: true
    restart_policy: always
    ports:
      - "{{ 3000 + item }}:3000" 
    volumes:
      - '/containers_vols/grafana/config/grafana.ini:/etc/grafana/grafana.ini:z'
    state: started
  loop:
    - 1
    - 2
    - 3 
  tags:
    - grafana