- name: pull image grafana
  podman_image:
    name: docker.io/grafana/grafana
    tag: latest

#- name: stop container if exist
#  shell: podman stop $(podman ps -q)
#  ignore_errors: true
#
#- name: remove container if exist
#  shell: podman rm $(podman ps -a -q)
#  ignore_errors: true

- name: Create data dir
  ansible.builtin.file:
    path: /containers_vols/grafana/config
    state: directory
    mode: '0755'

- name: update grafana config
  ansible.builtin.copy:
    src: ../templates/grafana.j2
    dest: /containers_vols/grafana/config/grafana.ini
    mode: '0664'

- name: Run Grafana1
  containers.podman.podman_container:
    name: grafana1
    image: docker.io/grafana/grafana
    detach: true
    restart_policy: always
    ports:
      - '3000:3000'
    volumes:
      - '/containers_vols/grafana/config/grafana.ini:/etc/grafana/grafana.ini:z'
    state: started