- name: pull image prometheus
  podman_image:
    name: docker.io/prom/prometheus

- name: Create data dir
  ansible.builtin.file:
    path: /containers_vols/prometheus/config
    state: directory
    mode: '0755'

- name: update prometheus config
  ansible.builtin.copy:
    src: ../templates/prometheus.j2
    dest: /containers_vols/prometheus/config/prometheus.yml
    owner: vagrant
    group: vagrant
    mode: '0664'

- name: Run Prometheus containers
  containers.podman.podman_container:
    name: "prometheus{{ item }}"
    image: docker.io/prom/prometheus
    detach: true
    restart_policy: always
    volume:
      - '/containers_vols/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:z'
    command: 
      --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "{{ 9090 + item }}:9090" 
    state: started
  loop:
    - 1
    - 2
    - 3 
  tags:
    - prometheus