---
- name: Pull Vault image
  podman_image:
    name: docker.io/hashicorp/vault
  
- name: Create data dir
  ansible.builtin.file:
    path: /containers_vols/vault/config
    state: directory
    mode: '0755'

- name: update vault config
  ansible.builtin.copy:
    src: ../templates/vault.hcl.j2
    dest: /containers_vols/vault/config/vault.hcl
    owner: vagrant
    group: vagrant
    mode: '0664'

#- name: Create Vault1 container
#  containers.podman.podman_container:
#    name: vault1
#    image: hashicorp/vault:latest
#    detach: true
#    restart_policy: always
#    ports:
#      - "8200:8200"
#    volumes:
#      - "/containers_vols/vault/config/:/vault/config:z"
#    cap_add:
#      - IPC_LOCK
#    env:
#      VAULT_DEV_ROOT_TOKEN_ID: "root"
#      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
#    command: "server"

- name: Run Vault containers
  containers.podman.podman_container:
    name: "vault{{ item }}"
    image: hashicorp/vault:latest
    detach: true
    restart_policy: always
    ports:
      - "{{ 8200 + item }}:8200"  # Dynamically assign unique host ports
    volumes:
      - "/containers_vols/vault/config/:/vault/config:z"
    cap_add:
      - IPC_LOCK
    env:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: "server"
    state: started
  loop:
    - 1
    - 2
    - 3  # Now includes 3 containers: vault1, vault2, vault3
  tags:
    - vault