# ansible/deploy.yml
---
- name: Install Podman on soufe1 and soube2
  hosts: all
  become: true
  roles:
    - sou_podman

- name: Deploy HAProxy and Vault container on soufe1
  hosts: soufe1
  become: true
  roles:
    - haproxy

- name: Deploy Prometheus container on soube2
  hosts: soube2
  become: true
  roles:
    - prometheus

- name: Deploy Grafana container on soube2
  hosts: soube2
  become: true
  roles:
    - grafana

- name: Deploy Vault container on soube2
  hosts: soube2
  become: true
  roles:
    - vault
