# ansible/deploy.yml
---
- name: Deploy Podman and HAProxy on soufe1
  hosts: soufe1
  become: true
  roles:
    - sou_podman
    - haproxy

- name: Deploy Podman, Prometheus, Vault and Grafana on soube2
  hosts: soube2
  become: true
  roles:
    - sou_podman
    - prometheus
    - grafana
